"""
Monetisation Helper Module
Provides utility functions for calculating volunteer work economic value.
"""

from datetime import datetime
from typing import Optional
from lib.db import fetchone, execute


def calculate_duration_days(start_date_str: str, end_date_str: str) -> int:
    """
    Calculate the number of days between start and end dates (inclusive).
    
    Args:
        start_date_str: Start date in 'YYYY-MM-DD' format
        end_date_str: End date in 'YYYY-MM-DD' format
    
    Returns:
        Number of days (inclusive), minimum 1
    
    Examples:
        >>> calculate_duration_days("2025-01-31", "2025-02-02")
        3  # Jan 31, Feb 1, Feb 2
        >>> calculate_duration_days("2024-12-31", "2025-01-01")
        2  # Dec 31, Jan 1
    """
    try:
        start = datetime.strptime(start_date_str, "%Y-%m-%d")
        end = datetime.strptime(end_date_str, "%Y-%m-%d")
        days = (end - start).days + 1  # +1 to include both start and end days
        return max(1, days)  # Minimum 1 day
    except Exception as e:
        print(f"Error calculating duration: {e}")
        return 1  # Default to 1 day on error


def calculate_volunteer_value(wage_rate: float, hours_per_day: float, duration_days: int) -> float:
    """
    Calculate the economic value generated by a single volunteer.
    
    Formula: wage_rate × hours_per_day × duration_days
    
    Args:
        wage_rate: Hourly wage rate in INR
        hours_per_day: Hours worked per day
        duration_days: Number of days worked
    
    Returns:
        Total value in INR
    """
    try:
        value = float(wage_rate) * float(hours_per_day) * int(duration_days)
        return round(value, 2)
    except Exception as e:
        print(f"Error calculating volunteer value: {e}")
        return 0.0


def calculate_task_value(wage_rate: float, hours_per_day: float, duration_days: int, num_volunteers: int) -> float:
    """
    Calculate the total economic value generated by a task.
    
    Formula: wage_rate × hours_per_day × duration_days × num_volunteers
    
    Args:
        wage_rate: Hourly wage rate in INR
        hours_per_day: Hours worked per day
        duration_days: Number of days the task runs
        num_volunteers: Number of approved volunteers who completed the work
    
    Returns:
        Total value in INR
    """
    try:
        value = float(wage_rate) * float(hours_per_day) * int(duration_days) * int(num_volunteers)
        return round(value, 2)
    except Exception as e:
        print(f"Error calculating task value: {e}")
        return 0.0


def format_currency(amount: float) -> str:
    """
    Format amount as Indian Rupees with proper comma separation.
    
    Args:
        amount: Amount in INR
    
    Returns:
        Formatted string like "₹1,23,456.00"
    """
    try:
        # Indian numbering system: last 3 digits, then groups of 2
        amount_str = f"{amount:,.2f}"
        parts = amount_str.split(".")
        integer_part = parts[0].replace(",", "")
        decimal_part = parts[1] if len(parts) > 1 else "00"
        
        if len(integer_part) <= 3:
            formatted = integer_part
        else:
            # Last 3 digits
            last_three = integer_part[-3:]
            remaining = integer_part[:-3]
            
            # Group remaining digits in pairs from right to left
            groups = []
            while remaining:
                groups.insert(0, remaining[-2:])
                remaining = remaining[:-2]
            
            formatted = ",".join(groups) + "," + last_three
        
        return f"₹{formatted}.{decimal_part}"
    except Exception as e:
        print(f"Error formatting currency: {e}")
        return f"₹{amount:.2f}"


def update_volunteer_total_value(volunteer_id: int) -> float:
    """
    Recalculate and update the total value generated by a volunteer.
    Only includes completed tasks (status='completed').
    
    Args:
        volunteer_id: ID of the volunteer
    
    Returns:
        Updated total value
    """
    try:
        # Sum all monetisation values for completed tasks only
        result = fetchone(
            """
            SELECT SUM(monetisation_value) as total
            FROM volunteer_acceptances
            WHERE volunteer_id = ? 
            AND status = 'completed'
            AND approval_status = 'approved'
            AND monetisation_value IS NOT NULL
            """,
            (volunteer_id,)
        )
        
        total_value = result.get('total', 0) or 0.0
        
        # Update volunteer record
        execute(
            "UPDATE volunteers SET total_value_generated = ? WHERE id = ?",
            (total_value, volunteer_id)
        )
        
        return total_value
    except Exception as e:
        print(f"Error updating volunteer total value: {e}")
        return 0.0


def get_task_wage_rate(task_id: int) -> Optional[float]:
    """
    Get the wage rate for a specific task.
    
    Args:
        task_id: ID of the task
    
    Returns:
        Wage rate in INR, or None if not found
    """
    try:
        task = fetchone("SELECT wage_rate FROM tasks WHERE id = ?", (task_id,))
        return task.get('wage_rate') if task else None
    except Exception as e:
        print(f"Error getting task wage rate: {e}")
        return None
